const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Cnds.CompareZElevation,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Camera3D.Exps.CameraYRotation,
		C3.Plugins.Camera3D.Exps.LookZ,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Shape3D.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetScale
	];
};
self.C3_JsPropNameTable = [
	{tilefloor: 0},
	{hp: 0},
	{"8Direction": 0},
	{Player: 0},
	{"3DCamera": 0},
	{Solid: 0},
	{wall: 0},
	{Keyboard: 0},
	{Flash: 0},
	{HandGun: 0},
	{aim: 0},
	{health: 0},
	{MoveTo: 0},
	{Demon: 0},
	{DemonSprt: 0},
	{Bullet: 0},
	{PlayerBullet: 0},
	{Mouse: 0},
	{Menu_bg: 0},
	{play_button: 0},
	{title_menu: 0},
	{Touch: 0},
	{loading_screen: 0},
	{amba: 0},
	{loading: 0},
	{red_bar: 0},
	{bar_darah: 0},
	{bar_design: 0},
	{heart_pixel: 0},
	{blood_vignette: 0},
	{Audio: 0},
	{hitam: 0},
	{QeMS: 0},
	{P: 0},
	{Variable1: 0},
	{Peluru: 0},
	{score: 0},
	{skor: 0},
	{SkullEmojidescription: 0},
	{back_to_menu: 0},
	{pngtreemodernstylishthreedimensionalcartoongamepixelpictureimage_1204458removebgpreview: 0},
	{keydown: 0},
	{keyup: 0},
	{keyright: 0},
	{keyleft: 0},
	{"—Pngtree—mobileFpsGameButtonSet1_": 0},
	{roof: 0},
	{Text: 0},
	{BulletsNoBackground: 0},
	{crate: 0},
	{Rotate: 0},
	{aid: 0},
	{Sensitivity: 0},
	{kill: 0}
];

self.InstanceType = {
	tilefloor: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	wall: class extends self.I3DShapeInstance {},
	Keyboard: class extends self.IInstance {},
	HandGun: class extends self.ISpriteInstance {},
	aim: class extends self.ISpriteInstance {},
	Demon: class extends self.I3DShapeInstance {},
	DemonSprt: class extends self.ISpriteInstance {},
	PlayerBullet: class extends self.I3DShapeInstance {},
	Mouse: class extends self.IInstance {},
	Menu_bg: class extends self.ISpriteInstance {},
	play_button: class extends self.ISpriteInstance {},
	title_menu: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	loading_screen: class extends self.ISpriteInstance {},
	amba: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	red_bar: class extends self.ISpriteInstance {},
	bar_darah: class extends self.ISpriteInstance {},
	bar_design: class extends self.ISpriteInstance {},
	heart_pixel: class extends self.ISpriteInstance {},
	blood_vignette: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	hitam: class extends self.ISpriteInstance {},
	QeMS: class extends self.ISpriteInstance {},
	P: class extends self.ITextInstance {},
	Peluru: class extends self.ITextInstance {},
	skor: class extends self.ITextInstance {},
	SkullEmojidescription: class extends self.ISpriteInstance {},
	back_to_menu: class extends self.ITextInstance {},
	pngtreemodernstylishthreedimensionalcartoongamepixelpictureimage_1204458removebgpreview: class extends self.ISpriteInstance {},
	keydown: class extends self.ISpriteInstance {},
	keyup: class extends self.ISpriteInstance {},
	keyright: class extends self.ISpriteInstance {},
	keyleft: class extends self.ISpriteInstance {},
	__InvalidName0__: class extends self.ISpriteInstance {},
	roof: class extends self.I3DShapeInstance {},
	Text: class extends self.ITextInstance {},
	BulletsNoBackground: class extends self.ISpriteInstance {},
	crate: class extends self.I3DShapeInstance {},
	aid: class extends self.I3DShapeInstance {}
}